apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: branch
      description: the branch for the git repo
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: my-first-image
      spec:
        type: image
        params:
          - name: url
            value: de.icr.io/jauninb-tekton/my-first-image
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: my-second-image
      spec:
        type: image
        params:
          - name: url
            value: de.icr.io/jauninb-tekton/my-second-image
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: imagebuild-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        # serviceAccounts:
        #   - taskName: pipeline-2-containerize-task
        #     serviceAccount: containerize-build-sa
        resources:
          - name: app-image-1
            resourceRef:
              name: my-first-image
          - name: app-image-2
            resourceRef:
              name: my-second-image
        params:
          - name: pipeline-pvc
            value: imagebuild-$(uid)-pvc
          - name: branch
            value: $(params.branch)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-run
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: manual-run
      template:
        name: trigger-template
