apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: vulnerability-advisor-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc - this is the volume where the files (Dockerfile etc..) are expected to be
      - name: continuous-delivery-context-configmap
        description: name of the configmap containing the continuous delivery pipeline context
        default: cd-config
      - name: continuous-delivery-context-secret
        description: name of the configmap containing the continuous delivery pipeline context secrets
        default: cd-secret
    resources:
      - name: image1
        type: image
      - name: image2
        type: image
  steps:
    - name: run-vulnerability-advisor-scan
      image: ibmcom/pipeline-base-image
      workingDir: /steps
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          export HOME="/root"
          ##########################################################################
          # Parse the image url to find information (region, namespace, image name)
          echo "image1 url: $(inputs.resources.image1.url)"
          echo "image1 digest: $(inputs.resources.image1.digest)"

          echo "image2 url: $(inputs.resources.image2.url)"
          echo "image2 digest: $(inputs.resources.image2.digest)"

          ls -l /
          ls -l -R /builder
          ls -l -R /workspace

      volumeMounts:
        - mountPath: /steps
          name: steps-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
