---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: doi-enabled-in-toolchain
spec:
  params:
  check:
    # Need only an image with jq
    image: ibmcom/pipeline-base-image:2.6
    command: ["/bin/bash", "-c"]
    args:
      - |
        if jq -e '.services[] | select(.service_id=="draservicebroker")' /cd-config/toolchain.json > /dev/null 2>&1; then
          # DevopsInisghts is integrated in the toolchain
          exit 0
        else
          # DevopsInisghts is not integrated in the toolchain
          exit 1
        fi
    volumeMounts:
      - mountPath: /cd-config
        name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
