apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: traceability
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
      default: "master"
    - name: cluster
      default: "mycluster"
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: traceability-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: traceability-$(uid)
      spec:
        pipelineRef:
          name: traceability
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: cluster
            value: $(params.cluster)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual
spec:
  params:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - bindings:
        - name: manual
      template:
        name: traceability
