apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: toolchain-dm
spec:
  params:
    - name: deployable-type
    - name: deployable-region-id
    - name: deployable-guid
    - name: deployable-cf-org-id
    - name: deployable-cf-space-id
    - name: deployable-rg-id
  tasks:
    - name: publish-deployable-task
      taskRef:
        name: otc-publish-deployable-mapping
      params:
        - name: deployable-type
          value: $(params.deployable-type)
        - name: deployable-region-id
          value: $(params.deployable-region-id)
        - name: deployable-guid
          value: $(params.deployable-guid)
        - name: deployable-cf-org-id
          value: $(params.deployable-cf-org-id)
        - name: deployable-cf-space-id
          value: $(params.deployable-cf-space-id)
        - name: deployable-rg-id
          value: $(params.deployable-rg-id)
