apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: skip-ci
spec:
  params:
    - name: ibmcloud-api
      default: 'https://cloud.ibm.com' 
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: commit-message
      default: ''
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: skip-ci
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: commit-message
            value: $(params.commit-message)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: revision
      value: "$(event.head_commit.id)"
    - name: branch
      value: "$(event.ref)"
    - name: commit-message
      value: |-
        $(event.head_commit.message)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-commit
spec:
  triggers:
    - binding:
        name: github-commit
      template:
        name: skip-ci
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual
spec:
  params:
    - name: repository
      value: "https://github.com/jauninb/sample"
    - name: revision
      value: ""
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-one-line
spec:
  params:
    - name: commit-message
      value: |-
        line1
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-two-line
spec:
  params:
    - name: commit-message
      value: |-
        line1
        line2
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-one-line
spec:
  triggers:
    - bindings:
        - name: manual
        - name: manual-one-line
      template:
        name: skip-ci
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-two-line
spec:
  triggers:
    - bindings:
        - name: manual
        - name: manual-two-line
      template:
        name: skip-ci
