apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: skip-ci
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: commit-message
      default: ''
  tasks:
    - name: clone-task
      taskRef:
        name: clone-repo-task
      conditions:
        - conditionRef: skip-ci
          params:
            - name: commit-message
              value: $(params.commit-message)
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
