apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: branch
      description: the branch for the git repo
  resources:
  - name: app-image
    type: image
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: pipeline-va-task
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: scanReportFile
          value: 'app-image-va-report.json'
        - name: maxIteration
          value: '6'
        - name: sleepTime
          value: '3'
        # - name: failOnScannedIssues
        #   value: 'false'
      workspaces:
        - name: workspace
          workspace: pipeline-ws
      resources:
        inputs:
          - name: image
            resource: app-image
