apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: param1
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipeline-run-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        params:
          - name: param1
            value: $(params.param1)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-1
spec:
  params:
    - name: param1
      value: "tb-1"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-2
spec:
  params:
    - name: param1
      value: "tb-2"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-3
spec:
  params:
    - name: param1
      value: "tb-3"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - bindings:
        - name: trigger-binding-1
        - name: trigger-binding-3
        - name: trigger-binding-2
      template:
        name: trigger-template
