apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: ibmcloud-login
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc - this is the volume where the files (Dockerfile etc..) are expected to be
      - name: ibmcloudApi
        description: the ibmcloud api
        default: https://cloud.ibm.com
      - name: continuous-delivery-context-secret
        description: name of the configmap containing the continuous delivery pipeline context secrets
        default: cd-secret
      - name: resourceGroup
        description: target resource group (name or id) for the ibmcloud login operation
        default: ''
      - name: clusterRegion
        description: (optional) the ibmcloud region hosting the cluster (if none is found it will default to the toolchain region)
        default: ''
      - name: clusterPipelineResourcesDirectoryFallback
        description: directory in the task-pvc that will be used as a fallback mechanism to store the kubeconfig file
        default: .tekton-cluster-pipeline-resources
    resources:
      # Will be set as optional when tekton version support it
      - name: cluster
        type: cluster
  outputs:
    resources:
      # Will be set as optional when tekton version support it
      - name: cluster
        type: cluster    
  steps:
    - name: setup
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.continuous-delivery-context-secret)
              key: API_KEY
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          export HOME="/root"
          ibmcloud plugin list
          ##########################################################################
          export IBMCLOUD_HOME=/artifacts/.ibmcloudcli
          mkdir -p $IBMCLOUD_HOME
          ibmcloud plugin list
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
        - key: toolchain.json
          path: toolchain.json