apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: toolchainRegion
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south
    - name: toolchainId
      description: The IBM Cloud Kubernetes cluster region
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: pipeline-pvc
          value: pipelinerun-$(uid)-pvc
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: toolchainRegion
          value: $(params.toolchainRegion)
        - name: toolchainId
          value: $(params.toolchainId)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-dev
spec:
  params:
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-staging
spec:
  params:
    - name: revision
      value: "integration"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-dev
spec:
  triggers:
    - binding:
        name: trigger-binding-dev
      template:
        name: trigger-template
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-staging
spec:
  triggers:
    - binding:
        name: trigger-binding-staging
      template:
        name: trigger-template