apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
  resources:
  # - name: app-image
  #   type: image
  - name: target-cluster
    type: cluster
  tasks:
    - name: pipeline-0-setup-task
      taskRef:
        name: ibmcloud-login
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: clusterPipelineResourcesDirectoryFallback
          value: .tekton-clusters
      resources:          
        inputs:
          - name: cluster
            resource: target-cluster
        outputs:
          - name: cluster
            resource: target-cluster
    - name: pipeline-1-ibmcloud-test
      taskRef:
        name: ibmcloud-login
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: task-pvc-mountpath
          value: /pipelinerun
        - name: clusterPipelineResourcesDirectory
          value: /pipelinerun/.tekton-clusters
        - name: script
          value: |
            echo "Here is the kubectl cluster-info:"
            kubectl cluster-info
            echo "I am listing the namespaces"
            kubectl get namespaces
            echo "Here is the kubectl cluster-info:"
      resources:          
        inputs:
          - name: cluster
            resource: target-cluster
            from:
              - pipeline-0-setup-task
