apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubernetes-context-execution
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc - this is the volume valid for the lifetime of the pipelinerun
      - name: task-pvc-mountpath
        default: /artifacts
      - name: clusterPipelineResourcesDirectory
        description: directory in which the kubeconfig file(s) for clusterPipelineResources are available
        default: /workspace
    resources:
      - name: cluster
        type: cluster
  stepTemplate:
    env:
      # As Cluster Pipeline Resources are not properly updated after kubernetes cluster setup
      # use the kubeconfig copy fallback provided by fetch-iks-cluster-context task
      - name: KUBECONFIG
        value: $(inputs.params.clusterPipelineResourcesDirectory)/$(inputs.resources.cluster.name)/kubeconfig
  steps:
    - name: dosomething
      image: ibmcom/pipeline-base-image
      workingDir: $(inputs.params.task-pvc-mountpath)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "List K8S ns"
          kubectl get ns
      volumeMounts:
        - mountPath: $(inputs.params.task-pvc-mountpath)
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
