apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubernetes-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc - this is the volume where the files (Dockerfile etc..) are expected to be
    resources:
      - name: cluster
        type: cluster
  steps:
    - name: dosomething
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "** kubeconfig content **"
          cat /workspace/$(inputs.resources.cluster.name)/kubeconfig
      volumeMounts:
        - mountPath: /steps
          name: steps-volume
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
        - key: toolchain.json
          path: toolchain.json